.\" Manpage for raspiBackupInstallUI
.\" Contact framp@linux-tips-and-tricks.de to correct errors or typos.
.TH man 1 "13 May 2026" "1.0" "raspiBackup man page"
.SH NAME
raspiBackupiInstallUI \- Install and configure raspiBackup
.SH SYNOPSIS
raspiBackupInstallUI
.SH DESCRIPTION
@TBD
Install and configure raspiBackup
.SH OPTIONS
None
.SH SEE ALSO
raspiBackup(1)
.SH BUGS
No known bugs.
.SH AUTHOR
framp (raspibackup@linux-tips-and-tricks.de)
