.\" Manpage for raspiBackup
.\" Contact framp@linux-tips-and-tricks.de to correct errors or typos.
.TH man 1 "13 May 2026" "1.0" "raspiBackup man page"
.SH NAME
raspiRackup \- create Raspberry backups
.SH SYNOPSIS
raspiBackup [backupPartition]
.SH DESCRIPTION
raspiBackup creates backup versions of a running Raspberry
.SH OPTIONS
backupPartition: Partition the backup to create on
.SH SEE ALSO
raspiBackupInstallUI(1)
.SH BUGS
No known bugs.
.SH AUTHOR
framp (framp@linux-tips-and-tricks.de)
