#!/usr/bin/env bash

#######################################################################################################################
#
# Script to download, install, configure and uninstall raspiBackup.sh.
#
# Visit http://www.linux-tips-and-tricks.de/raspiBackup for latest code and other details
#
#######################################################################################################################
#
#    Copyright (c) 2020 framp at linux-tips-and-tricks dot de
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#######################################################################################################################

MYSELF=${0##*/}
URL="https://www.linux-tips-and-tricks.de"
INSTALLER="raspiBackupInstallUI.sh"
INSTALLER_DOWNLOAD_URL="$URL/$INSTALLER"

function cleanup() {
	[[ -f "$MYSELF" ]] && rm -f "$MYSELF" &>/dev/null
	[[ -f "./$INSTALLER" ]] && rm -f "./$INSTALLER" &>/dev/null
	cd "$CURRENT_DIR"
}

if (( $UID != 0 )); then
	echo "Root access required. Please use sudo."
	exit 1
fi

CURRENT_DIR=$(pwd)

trap cleanup SIGINT SIGTERM EXIT

cd ~
# download and invoke installer
curl -sLO "$INSTALLER_DOWNLOAD_URL" && sudo bash "./$INSTALLER"
