name: ShellCheck
on: [push]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          # This tells the robot to check all .sh files
          scandir: './*.sh ./installation/*.sh'
          severity: warning
